name: Release

on:
  push:
    tags:
      - 'v*'             # запуск при пуше тега вида v1.0.0, v2.3.4 и т.д.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build for Windows (exe)
        run: |
          GOOS=windows GOARCH=amd64 go build -o myapp.exe main.go

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          files: myapp.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
